apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-controller
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: metallb
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          action: keep
          regex: controller
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-speaker
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
      app.kubernetes.io/name: metallb
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          action: keep
          regex: speaker
    - port: frrmetrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          action: keep
          regex: frr-metrics