apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb-controller
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app: metallb
      component: controller
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metallb-speaker
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app: metallb
      component: speaker
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s