apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "juice-shop.fullname" . }}-backend-traffic-policy
  namespace: {{ .Values.argocd.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "juice-shop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    name: {{ include "juice-shop.fullname" . }}-argocd-httproute
    kind: HTTPRoute
  timeout:
    http:
      requestTimeout: 0s