{{- if .Values.monitoring.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "juice-shop.fullname" . }}-monitoring-ingress
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "juice-shop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # Force HTTPS redirect
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"


spec:
  ingressClassName: {{ .Values.monitoring.ingress.className | default "nginx" }}
  rules:
    - host: {{.Values.monitoring.ingress.host}}
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  number: 9090
          - path: /alertmanager
            pathType: Prefix
            backend:
              service:
                name: alertmanager-operated
                port:
                  number: 9093
  {{- if .Values.monitoring.ingress.tls }}
  tls:
    {{- toYaml .Values.monitoring.ingress.tls | nindent 4  }}
  {{- end }}
{{- end }}
