apiVersion: v1
kind: Pod
metadata:
  name: attacker
  namespace: default
spec:
  nodeSelector:
    node-role: app
  containers:
  - name: attacker
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 3600"]
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /