apiVersion: v1
kind: Service
metadata:
  name: elastic-operator-metrics
  namespace: elastic-system
  labels:
    app.kubernetes.io/name: elastic-operator-metrics
spec:
  selector:
    app.kubernetes.io/name: elastic-operator
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eck-operator
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - elastic-system
  selector:
    matchLabels:
      app.kubernetes.io/name: elastic-operator-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s