apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.19.14
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      nodeSelector:
        node-role: logging
      tolerations:
        - key: node-role
          operator: Equal
          value: logging
          effect: NoSchedule
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m