replicaCount: 2

image:
  repository: ghcr.io/knightcrawlerr/juice-shop
  pullPolicy: Always
  tag: "sha-f5ed6c4144f2aa4c5f0905f6ace10e2247aa5b54"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 3000

networkPolicy:
  enabled: true

app:
  gateway:
    name: eg
    enabled: true
    host: juice-shop.com
    namespace: envoy-gateway-system
    tls:
      - secretName: juice-shop-tls

argocd:
  name: argocd
  namespace: argocd
  host: argocd.juice-shop.com


monitoring:
  name: monitoring
  namespace: monitoring
  host: monitoring.juice-shop.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
